# Generated by Django 3.0.8 on 2020-07-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200726_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='quantity',
        ),
    ]
